# Generated by Django 2.0.3 on 2018-11-05 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(blank=True, max_length=64, null=True)),
                ('home_number', models.CharField(blank=True, max_length=8, null=True)),
                ('flat_number', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=64, unique=True)),
                ('type_email', models.IntegerField(choices=[(1, 'Home'), (2, 'Work'), (3, 'Other')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(blank=True, max_length=32, null=True)),
                ('note', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact_box.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('type_number', models.IntegerField(choices=[(1, 'Mobile'), (2, 'Work'), (3, 'Home'), (4, 'Other')])),
                ('persons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact_box.Person')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='persons',
            field=models.ManyToManyField(blank=True, related_name='group', to='contact_box.Person'),
        ),
        migrations.AddField(
            model_name='email',
            name='persons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact_box.Person'),
        ),
    ]
