# Generated by Django 2.0.3 on 2018-11-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_box', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='image',
        ),
    ]
