# Generated by Django 2.0.3 on 2018-11-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_box', '0002_remove_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='type_email',
            field=models.IntegerField(choices=[(1, 'Home'), (2, 'Work'), (3, 'Other')]),
        ),
    ]
